OpenCBDC Transaction Processor: cbdc::sentinel::controller Class Reference
cbdc::sentinel::controller Class Reference
Sentinel implementation.
#include <controller.hpp>
Public Member Functions
controller ()=delete
controller (const controller &)=delete
auto operator= (const controller &) -> controller &=delete
controller (controller &&)=delete
auto operator= (controller &&) -> controller &=delete
controller (uint32_t sentinel_id, config::options opts, std::shared_ptr< logging::log > logger)
Constructor.
~controller () override=default
auto init () -> bool
Initializes the controller.
auto execute_transaction (transaction::full_tx tx) -> std::optional< cbdc::sentinel::execute_response > override
Validate transaction, forward it to shards for processing, and return the validation result to send back to the originating client.
auto validate_transaction (transaction::full_tx tx) -> std::optional< validate_response > override
Validate transaction and generate a sentinel attestation if the transaction is valid.
Public Member Functions inherited from cbdc::sentinel::interface
virtual ~interface ()=default
interface ()=default
interface (const interface &)=delete
auto operator= (const interface &) -> interface &=delete
interface (interface &&)=delete
auto operator= (interface &&) -> interface &=delete
virtual auto execute_transaction (transaction::full_tx tx) -> std::optional< execute_response >=0
Validate transaction on the sentinel, and forward it to the coordinator or shards depending on the implementation.
virtual auto validate_transaction (transaction::full_tx tx) -> std::optional< validate_response >=0
Validate transaction and generate a sentinel attestation if the transaction is valid.
Detailed Description
Sentinel implementation.
Definition at line 21 of file atomizer/sentinel/controller.hpp.
Constructor & Destructor Documentation
controller() [1/4]
cbdc::sentinel::controller::controller () delete
controller() [2/4]
cbdc::sentinel::controller::controller (const controller &) delete
controller() [3/4]
cbdc::sentinel::controller::controller (controller &&) delete
controller() [4/4]
cbdc::sentinel::controller::controller (uint32_t sentinel_id, config::options opts, std::shared_ptr< logging::log > logger)
Constructor.
Parameters
sentinel_id the running ID of this shard.
opts pointer to configuration options.
logger pointer shared logger.
Definition at line 15 of file atomizer/sentinel/controller.cpp.
~controller()
cbdc::sentinel::controller::~controller () override default
Member Function Documentation
execute_transaction()
auto cbdc::sentinel::controller::execute_transaction (transaction::full_tx tx) -> std::optional<cbdc::sentinel::execute_response> override virtual
Validate transaction, forward it to shards for processing, and return the validation result to send back to the originating client.
Parameters
tx transaction to execute.
Returns
response with the transaction status to send to the client.
Implements cbdc::sentinel::interface.
Definition at line 86 of file atomizer/sentinel/controller.cpp.
References cbdc::transaction::validation::check_tx(), cbdc::sentinel::pending, cbdc::sentinel::static_invalid, cbdc::to_string(), and cbdc::transaction::tx_id().
init()
auto cbdc::sentinel::controller::init () -> bool
Initializes the controller.
Establishes connections to the shards
Returns
true if initialization succeeded.
Definition at line 22 of file atomizer/sentinel/controller.cpp.
References cbdc::client::init(), cbdc::pubkey_from_privkey(), and cbdc::to_string().
operator=() [1/2]
auto cbdc::sentinel::controller::operator= (const controller &) -> controller &=delete delete
operator=() [2/2]
auto cbdc::sentinel::controller::operator= (controller &&) -> controller &=delete delete
validate_transaction()
auto cbdc::sentinel::controller::validate_transaction (transaction::full_tx tx) -> std::optional<validate_response> override virtual
Validate transaction and generate a sentinel attestation if the transaction is valid.
Parameters
tx transaction to validate and attest to.
Returns
sentinel attestation for the given transaction, or std::nullopt if the transaction is invalid.
Implements cbdc::sentinel::interface.
Definition at line 118 of file atomizer/sentinel/controller.cpp.
References cbdc::transaction::validation::check_tx().
The documentation for this class was generated from the following files:
atomizer/sentinel/controller.hpp
atomizer/sentinel/controller.cpp